steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'gcr.io/avian-pact-423923-v6/$_SERVICE_NAME:$COMMIT_SHA', '.']
  

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/avian-pact-423923-v6/$_SERVICE_NAME:$COMMIT_SHA']
  
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "gcr.io/avian-pact-423923-v6/$_SERVICE_NAME:$COMMIT_SHA",
        "--region",
        "$_DEPLOY_REGION",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/avian-pact-423923-v6/$_SERVICE_NAME:$COMMIT_SHA

substitutions:
  _SERVICE_NAME: simple-spring-app-cicd
  _DEPLOY_REGION: us-central1
